server.port=8080

# Corrected Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/todo_app_db
spring.datasource.username=todouser
spring.datasource.password=todo@123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Optional SQL Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT and Spring Boot
jwt.secret=qzHgRacOZFOFSZY3lqRWgFtzxcI4whtz68iqr5jecOo=
jwt.expiration=86400000
spring.main.log-startup-info=false

# Enable JPA Repositories
spring.data.jpa.repositories.enabled=true

# Security Debugging
logging.level.org.springframework.security=DEBUG

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ganesh.rawool@nonstopio.com
spring.mail.password=buwa aeuk vfdl yiac
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
